name: Github Action Test
on: [ push ]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Sending Report Html
              uses: appleboy/telegram-action@master
              with:
                  to: 7541742800
                  token: 8444003669:AAHZ0AynBvuR6pfogoim-sV8xEYwP1ytpko
                  document: test.html

                  message: |+
                      📄 New Report Attached
                      Project: GuitarEik Web
                      Status: File sent successfully.

                         
            - name: Image Sending
              uses: appleboy/telegram-action@master
              with:
                  to: 7541742800
                  token: 8444003669:AAHZ0AynBvuR6pfogoim-sV8xEYwP1ytpko
                  document: image.png
                  message: "Commit: ${{ github.event.head_commit.message }}"
