name: Flutter Multi-Platform Build
on: [ push ]

jobs:
    window-build:
        runs-on: windows-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable

            - name: Get Pub
              working-directory: ./all_in_one
              run: flutter pub get

            - name: Enable Window
              run: flutter config --enable-windows-desktop

            - name: Build Window
              working-directory: ./all_in_one
              run: flutter build windows --release

            - name: Archive Build
              shell: bash
              run: |
                  # all_in_one folder ထဲကို အရင်ဝင်ရပါမယ်
                  cd all_in_one/build/windows/x64/runner/Release
                  tar -cvzf ../../../../GuitarEik_Windows.zip *
            - name: Upload Zip File
              uses: actions/upload-artifact@v4
              with:
                  name: windows-zip
                  path: GuitarEik_Windows.zip

    send-telegram:
        needs: window-build
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4.1.7
              with:
                  name: windows-zip

            - name: Window File Sending
              uses: appleboy/telegram-action@master
              with:
                  to: 7541742800
                  token: 8444003669:AAHZ0AynBvuR6pfogoim-sV8xEYwP1ytpko
                  document: GuitarEik_Windows.zip
                  message: |
                      🖥️ Windows Build Complete!
                      Project: GuitarEik Web
